### ISSUE TITLE
thread 'Download Pool' panicked

### ISSUE THREAD

**Issue by Goury** [AchetaGames/Epic-Asset-Manager#277]
**Describe the bug**
```
thread 'Download Pool' panicked at 'range end index 46174 out of range for slice of length 46170', /run/build/epic_asset_manager/vendor/egs-api/src/api/utils.rs:43:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Download Pool' panicked at 'range end index 46174 out of range for slice of length 46170', /run/build/epic_asset_manager/vendor/egs-api/src/api/utils.rs:43:24
```

**To Reproduce**
1. Go to Advanced Magic FX 12
2. Try to download the latest version
3. F

**Expected behavior**
Download goes as expected

**Screenshots**
![Снимок экрана от 2024-09-15 22-22-54](https://github.com/user-attachments/assets/1dc32864-2787-4c43-a0e6-18994bc48590)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, Unity 7
 - Version 3.8.4

**Comment by Goury** [comment]
Also newer versions don't seem to be available via update

**Comment by Goury** [comment]
Manually building and running 3.8.6 seems to be solving the problem
